/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.model.jooq.tables.pojos;


import edu.java.scrapper.model.jooq.enums.State;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgChat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private State state;

    public TgChat() {}

    public TgChat(TgChat value) {
        this.id = value.id;
        this.state = value.state;
    }

    @ConstructorProperties({ "id", "state" })
    public TgChat(
        @NotNull Long id,
        @Nullable State state
    ) {
        this.id = id;
        this.state = state;
    }

    /**
     * Getter for <code>TG_CHAT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>TG_CHAT.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>TG_CHAT.STATE</code>.
     */
    @Nullable
    public State getState() {
        return this.state;
    }

    /**
     * Setter for <code>TG_CHAT.STATE</code>.
     */
    public void setState(@Nullable State state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TgChat other = (TgChat) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgChat (");

        sb.append(id);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
