/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.model.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TgChatLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tgChatId;
    private Long linkId;

    public TgChatLink() {}

    public TgChatLink(TgChatLink value) {
        this.tgChatId = value.tgChatId;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({ "tgChatId", "linkId" })
    public TgChatLink(
        @NotNull Long tgChatId,
        @NotNull Long linkId
    ) {
        this.tgChatId = tgChatId;
        this.linkId = linkId;
    }

    /**
     * Getter for <code>TG_CHAT_LINK.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return this.tgChatId;
    }

    /**
     * Setter for <code>TG_CHAT_LINK.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long tgChatId) {
        this.tgChatId = tgChatId;
    }

    /**
     * Getter for <code>TG_CHAT_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>TG_CHAT_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TgChatLink other = (TgChatLink) obj;
        if (this.tgChatId == null) {
            if (other.tgChatId != null)
                return false;
        }
        else if (!this.tgChatId.equals(other.tgChatId))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tgChatId == null) ? 0 : this.tgChatId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgChatLink (");

        sb.append(tgChatId);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
