--liquibase formatted sql

--changeset nevinture:1
create table if not exists stackoverflow_link (
    id int primary key generated by default as identity,
    url text unique not null,
    last_check_at timestamp with time zone not null,
    last_update_at timestamp  with time zone not null,
    answers int default 0
);
