app:
  scheduler:
    enable: false
    interval: 2m
    force-check-delay: 2m
  git-base-url: https://api.github.com/repos/
  sof-base-url: https://api.stackexchange.com/2.3/questions/
  bot-api-base-url: http://localhost:8090
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
