app:
  scheduler:
    enable: false
    interval: 1h
    force-check-delay: 1h
  git-base-url: https://api.github.com/repos/
  sof-base-url: https://api.stackexchange.com/2.3/questions/
  bot-api-base-url: http://localhost:8090
  database-access-type: jpa
  retry-policy:
    mode: linear
    codes:
      - not_found
      - bad_request
  kafka:
    acks-mode: 1
    client-id: scrapper
    delivery-timeout: 2m
    linger-ms: 12_000
    batch-size: 100_000
    max-in-flight-per-connection: 5
    boot-strap-servers: localhost:9092,localhost:9093
  use-queue: true

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-bucket
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=1d
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
#  level:
#    root: debug
#    org:
#      springframework:
#        web: trace
#      apache: trace
#debug: true

springdoc:
  swagger-ui:
    path: /swagger-ui

#rate-limit
bucket4j:
  enabled: true
  cache-to-use: jcache
  filters:
    - cache-name: rate-limit-bucket
      url: /api/.*
      rate-limits:
      - cache-key: getRemoteAddr()
        bandwidths:
          - capacity: 300
            time: 1
            unit: days
