/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.model.jooq;

import edu.java.scrapper.model.jooq.tables.GitRepository;
import edu.java.scrapper.model.jooq.tables.Link;
import edu.java.scrapper.model.jooq.tables.StackoverflowQuestion;
import edu.java.scrapper.model.jooq.tables.TgChat;
import edu.java.scrapper.model.jooq.tables.TgChatLink;
import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>GIT_REPOSITORY</code>.
     */
    public static final GitRepository GIT_REPOSITORY = GitRepository.GIT_REPOSITORY;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>STACKOVERFLOW_QUESTION</code>.
     */
    public static final StackoverflowQuestion STACKOVERFLOW_QUESTION = StackoverflowQuestion.STACKOVERFLOW_QUESTION;

    /**
     * The table <code>TG_CHAT</code>.
     */
    public static final TgChat TG_CHAT = TgChat.TG_CHAT;

    /**
     * The table <code>TG_CHAT_LINK</code>.
     */
    public static final TgChatLink TG_CHAT_LINK = TgChatLink.TG_CHAT_LINK;
}
