/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.model.jooq.tables;


import edu.java.scrapper.model.jooq.DefaultSchema;
import edu.java.scrapper.model.jooq.Keys;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GitRepository extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GIT_REPOSITORY</code>
     */
    public static final GitRepository GIT_REPOSITORY = new GitRepository();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>GIT_REPOSITORY.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>GIT_REPOSITORY.LINK_ID</code>.
     */
    public final TableField<Record, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>GIT_REPOSITORY.URN</code>.
     */
    public final TableField<Record, String> URN = createField(DSL.name("URN"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>GIT_REPOSITORY.LAST_CHECK_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_CHECK_AT = createField(DSL.name("LAST_CHECK_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>GIT_REPOSITORY.LAST_UPDATE_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_UPDATE_AT = createField(DSL.name("LAST_UPDATE_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>GIT_REPOSITORY.LAST_PUSH_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_PUSH_AT = createField(DSL.name("LAST_PUSH_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private GitRepository(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private GitRepository(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GIT_REPOSITORY</code> table reference
     */
    public GitRepository(String alias) {
        this(DSL.name(alias), GIT_REPOSITORY);
    }

    /**
     * Create an aliased <code>GIT_REPOSITORY</code> table reference
     */
    public GitRepository(Name alias) {
        this(alias, GIT_REPOSITORY);
    }

    /**
     * Create a <code>GIT_REPOSITORY</code> table reference
     */
    public GitRepository() {
        this(DSL.name("GIT_REPOSITORY"), null);
    }

    public <O extends Record> GitRepository(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, GIT_REPOSITORY);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    @NotNull
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_392);
    }

    @Override
    @NotNull
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_39);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_39);

        return _link;
    }

    @Override
    @NotNull
    public GitRepository as(String alias) {
        return new GitRepository(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GitRepository as(Name alias) {
        return new GitRepository(alias, this);
    }

    @Override
    @NotNull
    public GitRepository as(Table<?> alias) {
        return new GitRepository(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GitRepository rename(String name) {
        return new GitRepository(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GitRepository rename(Name name) {
        return new GitRepository(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GitRepository rename(Table<?> name) {
        return new GitRepository(name.getQualifiedName(), null);
    }
}
