/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.model.jooq.tables;

import edu.java.scrapper.model.jooq.DefaultSchema;
import edu.java.scrapper.model.jooq.Keys;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StackoverflowQuestion extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STACKOVERFLOW_QUESTION</code>
     */
    public static final StackoverflowQuestion STACKOVERFLOW_QUESTION = new StackoverflowQuestion();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>STACKOVERFLOW_QUESTION.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>STACKOVERFLOW_QUESTION.LINK_ID</code>.
     */
    public final TableField<Record, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>STACKOVERFLOW_QUESTION.URN</code>.
     */
    public final TableField<Record, String> URN = createField(DSL.name("URN"), SQLDataType.VARCHAR(1000000000).nullable(false), this, "");

    /**
     * The column <code>STACKOVERFLOW_QUESTION.LAST_CHECK_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_CHECK_AT = createField(DSL.name("LAST_CHECK_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>STACKOVERFLOW_QUESTION.LAST_UPDATE_AT</code>.
     */
    public final TableField<Record, OffsetDateTime> LAST_UPDATE_AT = createField(DSL.name("LAST_UPDATE_AT"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>STACKOVERFLOW_QUESTION.ANSWERS</code>.
     */
    public final TableField<Record, Integer> ANSWERS = createField(DSL.name("ANSWERS"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private StackoverflowQuestion(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private StackoverflowQuestion(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_QUESTION</code> table reference
     */
    public StackoverflowQuestion(String alias) {
        this(DSL.name(alias), STACKOVERFLOW_QUESTION);
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_QUESTION</code> table reference
     */
    public StackoverflowQuestion(Name alias) {
        this(alias, STACKOVERFLOW_QUESTION);
    }

    /**
     * Create a <code>STACKOVERFLOW_QUESTION</code> table reference
     */
    public StackoverflowQuestion() {
        this(DSL.name("STACKOVERFLOW_QUESTION"), null);
    }

    public <O extends Record> StackoverflowQuestion(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, STACKOVERFLOW_QUESTION);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    @NotNull
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_9D3);
    }

    @Override
    @NotNull
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_9D);
    }

    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_9D);

        return _link;
    }

    @Override
    @NotNull
    public StackoverflowQuestion as(String alias) {
        return new StackoverflowQuestion(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public StackoverflowQuestion as(Name alias) {
        return new StackoverflowQuestion(alias, this);
    }

    @Override
    @NotNull
    public StackoverflowQuestion as(Table<?> alias) {
        return new StackoverflowQuestion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowQuestion rename(String name) {
        return new StackoverflowQuestion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowQuestion rename(Name name) {
        return new StackoverflowQuestion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowQuestion rename(Table<?> name) {
        return new StackoverflowQuestion(name.getQualifiedName(), null);
    }
}
